AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance for Bell Streaming Platform'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  
  SubnetId:
    Type: String
  
  SecurityGroupId:
    Type: String
  
  GitHubPAT:
    Type: String
    NoEcho: true
  
  GitHubRepo:
    Type: String
    Default: rajv4rdhan/bellStreaming
  
  GitHubBranch:
    Type: String
    Default: main
  
  DopplerToken:
    Type: String
    NoEcho: true

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ecb62995f68bb549
      InstanceType: t3.medium
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          apt-get update -y
          apt-get upgrade -y
          
          # Install Git
          apt-get install -y git curl
          
          # Install Docker
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          systemctl enable docker
          systemctl start docker
          
          # Install Docker Compose
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
          # Install Doppler CLI
          apt-get update && apt-get install -y apt-transport-https ca-certificates gnupg
          curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list
          apt-get update && apt-get install -y doppler
          
          # Clone repository
          cd /opt
          git clone https://rajv4rdhan:${GitHubPAT}@github.com/${GitHubRepo}.git bell-streaming
          cd bell-streaming
          git checkout ${GitHubBranch}
          
          # Configure Doppler
          echo "${DopplerToken}" | doppler configure set token --scope /opt/bell-streaming
          
          # Start services with Doppler
          cd /opt/bell-streaming
          doppler run -- docker-compose -f docker-compose.prod.yml up -d
          
          # Create update script
          cat > /opt/bell-streaming/update.sh << 'UPDATE_EOF'
          #!/bin/bash
          cd /opt/bell-streaming
          git pull origin ${GitHubBranch}
          doppler run -- docker-compose -f docker-compose.prod.yml pull
          doppler run -- docker-compose -f docker-compose.prod.yml up -d --force-recreate
          docker image prune -f
          UPDATE_EOF
          
          chmod +x /opt/bell-streaming/update.sh
          
          # Create systemd service
          cat > /etc/systemd/system/bell-streaming.service << 'SERVICE_EOF'
          [Unit]
          Description=Bell Streaming Platform
          Requires=docker.service
          After=docker.service
          
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          WorkingDirectory=/opt/bell-streaming
          ExecStart=/usr/bin/doppler run -- /usr/local/bin/docker-compose -f docker-compose.prod.yml up -d
          ExecStop=/usr/local/bin/docker-compose -f docker-compose.prod.yml down
          
          [Install]
          WantedBy=multi-user.target
          SERVICE_EOF
          
          systemctl enable bell-streaming.service
          
          echo "Bell Streaming Platform deployed successfully!"
      Tags:
        - Key: Name
          Value: bell-streaming-ec2

Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'
  
  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'
  
  PublicDNS:
    Value: !GetAtt EC2Instance.PublicDnsName
    Export:
      Name: !Sub '${AWS::StackName}-PublicDNS'
