AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM resources for Bell Streaming EC2'

Resources:
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Tags:
        - Key: Name
          Value: BellStreaming-EC2-Role

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

Outputs:
  InstanceProfileArn:
    Description: 'Instance Profile ARN'
    Value: !GetAtt EC2InstanceProfile.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfileArn'
  
  InstanceProfileName:
    Description: 'Instance Profile Name'
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Sub '${AWS::StackName}-InstanceProfileName'
